baseURL = 'http://example.org/'
languageCode = 'es-Es'
title = 'Tarea Hugo'
theme = 'hugo-universal-theme'

# Lenguaje por defecto.
defaultContentLanguage = "es"

# Ponemos el autor de la página
[params]
author = "Andrés"

# Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
style = "custom"


# Logo
disabled_logo = false             #si lo ponemos a true saldra el logo_text
logo_text = "Hugo"
logo = "img/logo.png"
logo_small = "img/logo_small.png"

# Contacto
email = "saintandrews88@hotmail.com"
contact_form_ajax = false

enableRecaptchaInContactForm = true
googleRecaptchaKey = "site_key_for_google_recaptcha"

title = "Contact"
id = "contact"


# numero de palabras en el resumen del blog
summaryLength = 70

# Numero de post por página
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false


# ponemos el menú
[menu]

[[menu.main]] #INDICE
name = "Home"
identifier = "menu.home"
url = "/"
weight = 1

[[menu.main]]
name = "Opción 1: Pagina de inicio"
url = "/"
weight = 1
parent = "menu.home"

[[menu.main]] #MENU HUGO
name = "Opción 2: Definición de Hugo"
url = "/es/hugo/queEs/"
weight = 2
parent = "menu.home"

[[menu.main]] #MENU COMUNICACION
name = "Opción 3: Comunicación cliente-servidor"
url = "/es/cliente-servidor/comunicacion/"
weight = 3
parent = "menu.home"

[[menu.main]] #MENU PUZZLE
name = "Opción 4: Puzzle"
url = "/es/puzzle/puzz/"
weight = 4
parent = "menu.home"

[[menu.main]] #MENU SOBRE MI
name = "Opción 5: Sobre mi"
url = "/"
weight = 5
parent = "menu.home"


# PONEMOS EL TITULO DE CADA MENU Y LOS SUBMENUS
[[menu.main]]
name = "Hugo"
identifier = "menu.hugo"
url = "/img/hugo_menu.png"
weight = 2

[[menu.main]]
name = "Sobre Hugo"
identifier = "section.sobreHugo"
url = ""
weight = 1
parent = "menu.hugo"
post = 1


[[menu.main]]
name = "Instalación de Hugo"
identifier = "section.instalacion"
url = ""
weight = 2
parent = "menu.hugo"
post = 2

[[menu.main]]
name = "En sistema operativo Windows"
url = "/es/hugo/windows"
weight = 1
parent = "section.instalacion"


[[menu.main]]
name = "En sistema operativo Linux"
url = "/es/hugo/linux"
weight = 2
parent = "section.instalacion"


[[menu.main]]
name = "¿Qué es Hugo?"
url = "/es/hugo/queEs/"
weight = 1
parent = "section.sobreHugo"


[[menu.main]]
name = "Uso práctico"
url = "/es/hugo/uso"
weight = 2
parent = "section.sobreHugo"

[[menu.main]]
name = "Cliente-Servidor"
identifier = "menu.comunicacion"
url = "/img/cliente-servidor_menu.png"
weight = 3


[[menu.main]]
name = "Proceso de comunicación"
identifier = "section.comunicacion"
url = ""
weight = 1
parent = "menu.comunicacion"
post = 1


[[menu.main]]
name = "Comunicación Cliente-Servidor"
url = "/es/cliente-servidor/comunicacion/"
weight = 1
parent = "section.comunicacion"

[[menu.main]]
name = "Definiciones"
identifier = "section.definiciones"
url = ""
weight = 2
parent = "menu.comunicacion"
post = 2


[[menu.main]]
name = "Cliente"
url = "/es/cliente-servidor/cliente/"
weight = 1
parent = "section.definiciones"


[[menu.main]]
name = "Servidor"
url = "/es/cliente-servidor/servidor/"
weight = 2
parent = "section.definiciones"

[[menu.main]]
name = "Puzzle"
identifier = "menu"
url = "/es/puzzle/puzz/"
weight = 4


[[menu.main]]
name = "Sobre mi"
identifier = "menu.sobreMi"
url = "/es/sobre/sobre-mi/"
weight = 5


# Top bar menu

[[menu.topbar]]
weight = 1
name = "GitHub"
url = "https://github.com/Riverwing/hugo_tarea"
pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
weight = 2
name = "Facebook"
url = "http://facebook.com"
pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
weight = 3
name = "Linkedin"
url = "https://es.linkedin.com/in/andr%C3%A9s-ochoa-bueno-41ab651aa"
pre = "<i class='fab fa-2x fa-linkedin'></i>"

[[menu.topbar]]
weight = 4
name = "Email"
url = "mailto:saintandrews88@hotmail.com"
pre = "<i class='fas fa-2x fa-envelope'></i>"


# Habilitar top bar que diferenciará cuando se minimize la pantalla
[params.topbar]
enable = true
text = """
        <p class="hidden-sm hidden-xs">Contacta con nosostros a través del mail <a href="mailto:saintandrews88@hotmail.com"<a/>saintandrews88@hotmail.com
        </p>
      <p class="hidden-md hidden-lg">  
      <a href="mailto:saintandrews88@hotmail.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Habilitamos los widgets de la barra lateral
[params.widgets]
categories = true
tags = true
search = true

[params.see_more]
enable = true
icon = "far fa-file-alt"
title = "TAREA DE HUGO"
subtitle = "Sitio estático creado para la tarea solicitada en la asignatura de Desarrollo web en entorno servidor."
link_url = "http://manuel.infenlaces.com/dwes/hugo/docs/teoria/"
link_text = "TEORIA"

[params.recent_posts]
enable = true
title = "Nuestro Blog"
subtitle = "Este blog ha sido realizado sin ánimo de lucro. El objetivo es practicar con la herramienta Hugo. Espero que les guste, un saludo y muchas gracias."
hide_summary = false

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"
